Enable llvm builds for Qt 6.7+ on Windows
Squashed commit of the following:

commit 6f1994c35adf1df4fd5d1a6006f6bb1d3133f9aa
Author: Paul Colby <git@colby.id.au>
Date:   Wed Jan 8 08:38:28 2025 +1100

    Skip test collation for LLVM builds with Qt 6.7.3

    No sure why, lcov fails in this scenario, at least on GitHub
    runners:

    > error: Failed to load coverage: 'D:/a/_temp/coverage/src/lib/
    > CMakeFiles/QtSmithy.dir/model.cpp.obj': Malformed coverage data
    > error: Could not load coverage information

commit be93bc89e332041a16ebfa1dbde4e70172976eb5
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:12:03 2025 +1100

    Include Window LLVM builds for Qt 6.7+

commit 3423f3bad1f3ca53bc02b67febc8c204d099adbd
Author: Paul Colby <git@colby.id.au>
Date:   Tue Jan 7 23:05:48 2025 +1100

    Include Window LLVM builds for Qt 6.7+